QUICK_HELP = 'Enter `@Kumbh help` for help on using the kumbh.'

def HELP_MESSAGE(bot_handler)->str:
	english="Kumbh usage:\n`@Kumbh weather`\nGives the weather forecast for next three days\n`@Kumbh liveStation station-code`\nDisplays the details of train stopping at entered station-code in next 4 hours\n`@Kumbh findRoute train-number`\nDisplays the route of the entered train-number along with the scheduled arrival and departure at all intermediate stations\n`@Kumbh trainAtAllahabad train-number`\nDisplays the scheduled arrival, scheduled departure, expected arrival, actual departure and expected departure of entered train-number at Allahabad Jn Railway Station\n`@Kumbh trainFromTo source destination`\nDisplays details of all trains connecting source and destination station\n`@Kumbh bath`\nDisplays deatils of important events of kumbh\n`@Kumbh hospital`\nDisplays address of nearby hospitals ranked in ascending order of distance\n`@Kumbh emergencyContact`\nDisplays important emergency contacts\n`@Kumbh police`\nDisplays address of nearby police stations ranked in ascending order of distance\n`@Kumbh restaurant`\nDisplays address of nearby restaurant ranked in ascending order of distance\n`@Kumbh hotel`\nDisplays address of nearby hotels for lodging ranked in ascending order of distance\n`@Kumbh lost applicant_name applicant_aadhar lost_person_name lost_person_aadhar`\nSends an email to the official authority regarding the information about the lost person\n`@Kumbh imlost mob-number`\nSends a text sms to the specified mob-number stating you bot-number\n`@Kumbh bhajan`\nProvides detail to some random kumbh bhajan every time\n`@Kumbh news`\nDisplays the news headlines with their publication date and time\n`@Kumbh SOS`\nImmediately places a call to authority on your behalf\n"
	hindi="Kumbh usage:\n`@Kumbh weather`\nकुंभ का मौसम अगले तीन दिनों के लिए मौसम का पूर्वानुमान देता है\n`@Kumbh liveStation station-code`\nअगले 4 घंटों में दर्ज किए गए स्टेशन-कोड पर ट्रेन के रुकने का विवरण प्रदर्शित करता है\n`@Kumbh findRoute train-number`\nसभी इंटरमीडिएट स्टेशनों पर निर्धारित आगमन और प्रस्थान के साथ दर्ज की गई ट्रेन-संख्या का मार्ग प्रदर्शित करता है\n`@Kumbh trainAtAllahabad train-number`\nइलाहाबाद जंक्शन रेलवे स्टेशन पर प्रवेशित ट्रेन के नंबर के निर्धारित आगमन, निर्धारित प्रस्थान, अपेक्षित आगमन, निर्धारित प्रस्थान को प्रदर्शित करता है\n`@Kumbh trainFromTo source destination`\nस्रोत और गंतव्य स्टेशन को जोड़ने वाली सभी ट्रेनों का विवरण प्रदर्शित करता है\n`@Kumbh bath`\nकुंभ के महत्वपूर्ण स्नान की तिथियां प्रदर्शित करता है\n`@Kumbh hospital`\nदूरी के आरोही क्रम में पास के अस्पतालों के पते प्रदर्शित करता है\n`@Kumbh emergencyContact`\nमहत्वपूर्ण आपातकालीन संपर्क प्रदर्शित करता है\n`@Kumbh police`\nदूरी के आरोही क्रम में रैंक किए गए आस-पास के पुलिस स्टेशनों के पते प्रदर्शित करता है\n`@Kumbh restaurant`\nदूरी के आरोही क्रम में पास के रेस्तरां के पते प्रदर्शित करता है\n`@Kumbh hotel`\nदूरी के आरोही क्रम में रैंक करने के लिए आसपास के होटलों के पते प्रदर्शित करता है\n`@Kumbh lost applicant_name applicant_aadhar lost_person_name lost_person_aadhar`\nखोए हुए व्यक्ति की जानकारी के बारे में आधिकारिक प्राधिकारी को एक ईमेल भेजता है\n`@Kumbh imlost mob-number`\nनिर्दिष्ट मोबाइल-नंबर पर एक पाठ संदेश भेजता है जो आपको बॉट-नंबर बताता है\n`@Kumbh bhajan`\nहर बार कुछ यादृच्छिक कुंभों के वीडियो लिंक प्रदान करता है\n`@Kumbh news`\nसमाचार प्रकाशन को उनकी प्रकाशन तिथि और समय के साथ प्रदर्शित करता है\n`@Kumbh SOS`\nतुरंत अपनी ओर से प्राधिकरण को फ़ोन कॉल करें"

	final_msg=english+hindi
	return final_msg
        
        
                      
